services:

  nginx:
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/local.conf.template:/etc/nginx/templates/default.conf.template:ro

  certbot:
    profiles:
      - disabled